version: '3.8'
services: 
    db01:
      build:
        context: ./Docker-files/db
      image: walidzaouch/mysqldb
      container_name: mysqldb
      ports: 
        - "3306:3306"
      volumes:
        - dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=vprodbpass

    cache01:
      image: memcached
      container_name: cache01
      ports: 
        - "11211:11211"

    mq01:
      image: rabbitmq
      container_name: mq01
      ports: 
        - "5672:5672"
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest

    app01:
      build:
        context: ./Docker-files/app
      image: walidzaouch/javaapp
      container_name: javaapp
      ports: 
        - "8080:8080"
      volumes:
        - appdata:/usr/local/tomcat/webapps



    web01:
      build:
        context: ./Docker-files/web
      image: walidzaouch/webapp
      container_name: webapp01
      ports: 
        - "80:80"

volumes: 
    dbdata: {}
    appdata: {}
