services: 
    db01:
      build:
        context: ./Docker-files/db
      image: walidzaouch/mysqldb
      ports: 
        - "3306:3306"
      volumes:
        - dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=vprodbpass

    cache01:
      image: memcached
      ports: 
        - "11211:11211"

    mq01:
      image: rabbitmq

      ports: 
        - "5672:5672"
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest

    app01:
      build:
        context: .
        dockerfile: ./Docker-files/app/Dockerfile
      image: walidzaouch/javaapp
      ports: 
        - "8080:8080"
      depends_on: 
        - db01
        - cache01
        - mq01
    web01:
      build:
        context: ./Docker-files/web
      image: walidzaouch/webapp
      ports: 
        - "80:80"

volumes: 
    dbdata: {}
    appdata: {}
