apiVersion: v1
kind: PersistentVolumeClaim
metadata: # we'll connect that to /var/lib/mysql
  name: db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard # Optional: uses default if omitted